"""update_created_by_to_user_id

Revision ID: 1371dd8762a0
Revises: f32d6f0e9e01
Create Date: 2025-07-16 19:46:35.560416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1371dd8762a0'
down_revision: Union[str, Sequence[str], None] = 'f32d6f0e9e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Önce users tablosundan email'e göre id'yi alacak bir subquery oluştur
    op.execute("""
        UPDATE events e 
        SET created_by = (SELECT id FROM users u WHERE u.email = e.created_by::text)
        WHERE e.created_by IS NOT NULL
    """)
    
    # Sonra kolonu integer'a dönüştür (USING ifadesi ile)
    op.execute("ALTER TABLE events ALTER COLUMN created_by TYPE INTEGER USING created_by::integer")
               
    op.create_foreign_key(None, 'events', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'created_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
