"""Add Member and ProjectMember models

Revision ID: 345ed2086eb2
Revises: 93a06b6f1452
Create Date: 2026-01-18 18:47:26.186525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345ed2086eb2'
down_revision: Union[str, Sequence[str], None] = '93a06b6f1452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# PostgreSQL enum tipi. Modul seviyesinde tanimli cunku upgrade ve downgrade
# ayni tipi paylasiyor.
#
# create_type=False onemli: add_column, Enum tipini KENDILIGINDEN OLUSTURMAZ
# (create_table olustururdu). Tip once acikca yaratilmazsa migration
# "type projecttype does not exist" ile patlar. Bu, seed'siz sifirdan kurulan
# her veritabaninda gorulur; dump'tan gelen kurulumlarda migration zaten
# atlandigi icin fark edilmiyordu.
project_type_enum = sa.Enum(
    'DEVELOPED_BY_MACS', 'SUPPORTED_BY_MACS', 'MEMBER_SHOWCASE',
    name='projecttype',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Adım 0: enum tipini olustur (checkfirst: tip zaten varsa dokunmaz)
    project_type_enum.create(op.get_bind(), checkfirst=True)

    # Adım 1: project_type kolonunu NULLABLE olarak ekle
    op.add_column('projects', sa.Column('project_type', project_type_enum, nullable=True))
    
    # Adım 2: Mevcut projelere default değer ver
    op.execute("UPDATE projects SET project_type = 'DEVELOPED_BY_MACS' WHERE project_type IS NULL")
    
    # Adım 3: Artık NOT NULL yapabiliriz
    op.alter_column('projects', 'project_type', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_type')
    # Kolon gidince tip de gitmeli, yoksa tekrar upgrade edilince artik bir
    # tip kalir ve enum degerleri degisirse catisir.
    project_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
