"""Add Member and ProjectMember models

Revision ID: 345ed2086eb2
Revises: 93a06b6f1452
Create Date: 2026-01-18 18:47:26.186525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345ed2086eb2'
down_revision: Union[str, Sequence[str], None] = '93a06b6f1452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Adım 1: project_type kolonunu NULLABLE olarak ekle
    op.add_column('projects', sa.Column('project_type', sa.Enum('DEVELOPED_BY_MACS', 'SUPPORTED_BY_MACS', 'MEMBER_SHOWCASE', name='projecttype'), nullable=True))
    
    # Adım 2: Mevcut projelere default değer ver
    op.execute("UPDATE projects SET project_type = 'DEVELOPED_BY_MACS' WHERE project_type IS NULL")
    
    # Adım 3: Artık NOT NULL yapabiliriz
    op.alter_column('projects', 'project_type', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_type')
    # ### end Alembic commands ###
