"""add technologies column to projects table

Revision ID: 39979e6a7ecf
Revises: aa4912bd54b0
Create Date: 2025-07-29 21:54:54.216800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39979e6a7ecf'
down_revision: Union[str, Sequence[str], None] = 'aa4912bd54b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('technologies', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'technologies')
    # ### end Alembic commands ###
