"""add_registration_and_directions_links_to_events

Revision ID: 40806a819458
Revises: 63091e5ab38a
Create Date: 2025-10-29 14:27:46.287051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40806a819458'
down_revision: Union[str, Sequence[str], None] = '63091e5ab38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('registration_link', sa.String(), nullable=True))
    op.add_column('events', sa.Column('directions_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'directions_link')
    op.drop_column('events', 'registration_link')
    # ### end Alembic commands ###
