"""fix_sponsors_column_names

Revision ID: 93a06b6f1452
Revises: db3a807312bf
Create Date: 2025-12-03 13:03:38.181929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a06b6f1452'
down_revision: Union[str, Sequence[str], None] = 'db3a807312bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('sponsors', sa.Column('address', sa.Text(), nullable=True))
    op.drop_column('sponsors', 'longtitude')
    op.drop_column('sponsors', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('adress', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sponsors', sa.Column('longtitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('sponsors', 'address')
    op.drop_column('sponsors', 'longitude')
    # ### end Alembic commands ###
