"""create_sponsors_table

Revision ID: db3a807312bf
Revises: 40806a819458
Create Date: 2025-12-03 12:55:16.868899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3a807312bf'
down_revision: Union[str, Sequence[str], None] = '40806a819458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('discount_info', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longtitude', sa.Float(), nullable=False),
    sa.Column('adress', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsors_category'), 'sponsors', ['category'], unique=False)
    op.create_index(op.f('ix_sponsors_id'), 'sponsors', ['id'], unique=False)
    op.create_index(op.f('ix_sponsors_name'), 'sponsors', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsors_name'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_id'), table_name='sponsors')
    op.drop_index(op.f('ix_sponsors_category'), table_name='sponsors')
    op.drop_table('sponsors')
    # ### end Alembic commands ###
